steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm
  args: ["install"]
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm
  args: ["build", "--prod"]
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm
  args :  ["npm", "config", "set", "prefix", "~/npm"]
- name: bash
  entrypoint: bash
  args: ['-c', 'export', 'PATH="$$PATH:$$HOME/npm/bin"']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"