env_variables:
  GULP_PATH: 'node_modules/gulp/bin/gulp.js'

service_account: cloudbuild@arno-web.iam.gserviceaccount.com

steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm
  args: ["install"]
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm
  args: ["install", "gulp", "-g"]
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm
  args: ["run", "build", "--prod"]
- name: bash
  entrypoint: bash
  args: ['-c', 'export', 'PATH="$$PATH:$$HOME/npm/bin"']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY
